export const products = [
  {
    id: 1,
    title: "Острый Цыпленок",
    price: 50,
    amount: 5,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 2,
    title: "Паназия",
    price: 70,
    amount: 10,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 3,
    title: "Супер Sykpyn",
    price: 80,
    amount: 15,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 4,
    title: "Любимая пицца Димаса",
    price: 90,
    amount: 20,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 5,
    title: "Мясное удовольствие",
    price: 100,
    amount: 25,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 6,
    title: "Мандариновая",
    price: 50,
    amount: 5,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 7,
    title: "Любимая Карбонара",
    price: 70,
    amount: 10,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 8,
    title: "Восемб Сыров",
    price: 80,
    amount: 15,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 9,
    title: "Цыпленок Барбекю",
    price: 90,
    amount: 20,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 10,
    title: "Цыпленок Рэнч",
    price: 100,
    amount: 25,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 11,
    title: "Маргарита",
    price: 90,
    amount: 20,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
  {
    id: 12,
    title: "Горчичная",
    price: 100,
    amount: 25,
    image: "https://i.ibb.co/hs2SdxJ/4.jpg",
  },
];
